import Nav from './components/Nav'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex justify-center'>
        <div className='w-5/6 md:w-2/3'>
          <div>
            <Nav />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
