import Nav from './components/Nav'
import './globals.css'
import { Hanken_Grotesk } from 'next/font/google'
import BackgroundParticles from './components/particles/BackgroundParticles';

const HankenGrotesk = Hanken_Grotesk({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={HankenGrotesk.style} className='flex justify-center bg-emerald-400'>
        <div className='w-5/6 md:w-2/3'>
          <div>
            <BackgroundParticles />
            <Nav />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
